# Site settings
course_name: Natural Language Processing
course_description: >
  In this course, students will be introduced to fundamental statistical and neural methods for
  language processing. The key topics to be covered are text pre-processing, text classification,
  named entity recognition, parts-of-speech tagging, lexical semantics, parsing, word sense
  disambiguation, semantic role labeling, coreference resolution, machine translation,
  conversational agents, and text generation.

  Students will also get an overview of numerous machine learning and deep learning algorithms
  necessary for efficiently solving language processing tasks. Finally, the students will learn to evaluate
  natural language processing tools for specific problems using a variety of evaluation measures.
course_semester: "Fall 2025"

# GitHub Pages config (project site)
url: "https://shwetanlp.github.io"          # ← domain ONLY
baseurl: "/cs421_fall2025"              # ← repo name with leading slash

schoolname: "UIC"
schoolurl: "https://uic.blackboard.com/"

address: |
  Department of Computer Science
  University of Illinois, Chicago
  USA

# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
  events:
    output: true
  lectures:
    output: true
  assignments:
    output: true
  announcements:
    output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
